yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: "8f0ed7eb354c0170205e06dbb0be720e9a006579"

npmScopes:
  strdst:
    npmPublishRegistry: "https://npm.pkg.github.com"
  strdstnet:
    npmPublishRegistry: "https://npm.pkg.github.com"
